export {
  DashboardSquare1Outlined as Dashboard2Outlined,
  User4Outlined as UsersOutlined,
  User4Outlined as UserOutlined,
  Comment1Outlined as CommentsOutlined,
  Briefcase1Outlined as BriefcaseOutlined,
  Gear1Outlined as GearOutlined,
  Search1Outlined as SearchOutlined,
  PlusOutlined,
  Pencil1Outlined as PencilOutlined,
  Trash3Outlined as TrashOutlined,
  XmarkOutlined as CloseOutlined,
  CheckCircle1Outlined as CheckmarkCircleOutlined,
  Ban2Outlined as WarningOutlined,
  QuestionMarkCircleOutlined as InformationOutlined,
  ArrowRightOutlined,
  ArrowLeftOutlined,
  ChevronDownOutlined,
  PhoneOutlined,
  AgendaOutlined as CalendarOutlined,
  Envelope1Outlined as EnvelopeOutlined,
  FileMultipleOutlined as FilesOutlined,
  Pencil1Outlined as WriteOutlined,
  Trophy1Outlined as TrophyOutlined,
  ExitOutlined,
  MenuCheesburgerOutlined as MenuOutlined,
  Funnel1Outlined as FunnelOutlined,
  RefreshCircle1ClockwiseOutlined as ReloadOutlined,
  ExpandArrow1Outlined as DragAndDropOutlined,
} from "@lineiconshq/free-icons";
